#!/usr/bin/python3
#import serial
import RPi.GPIO as GPIO
import time
import os
def init():
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(16, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
    GPIO.setup(26, GPIO.OUT)
    GPIO.output(26, 1)
    while True:
        time.sleep(0.03)
        if GPIO.input(16) == 1:
            print("System will now shutdown")
            os.system('poweroff')

if __name__ == '__main__':
    init()
